version: '3.8'

services:
  # Redis for Bloom filter persistence
  redis:
    image: redis:7-alpine
    container_name: username-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: username-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # k6 Load Testing
  k6:
    image: grafana/k6:latest
    container_name: username-k6
    volumes:
      - .:/scripts
    working_dir: /scripts
    profiles:
      - loadtest
    command: run simple-loadtest.js
    depends_on:
      api:
        condition: service_healthy

volumes:
  redis_data:
